language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo install mdbook
  - mdbook --version
  - mdbook build
  - mdbook test
notifications:
  email:
    on_success: never
    on_failure: always